/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/office.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ofis(props) {
  const { nodes, materials } = useGLTF('models/office.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.762, 0, -0.156]}>
        <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.Office_Cha} />
        <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.Office_Cha_1} />
        <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials['BlackWood.001']} />
        <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials['BlackCoatSteel.001']} />
        <mesh geometry={nodes['Node-Mesh_4'].geometry} material={materials['GrayPlastic.001']} />
        <mesh geometry={nodes['Node-Mesh_5'].geometry} material={materials['WhiteSteelScrew.001']} />
        <mesh geometry={nodes['Node-Mesh_6'].geometry} material={materials['BlackPlastic.001']} />
        <mesh geometry={nodes['Node-Mesh_7'].geometry} material={materials['mat21.004']} />
        <mesh geometry={nodes['Node-Mesh_8'].geometry} material={materials['mat22.001']} />
        <mesh geometry={nodes['Node-Mesh_9'].geometry} material={materials['mat9.002']} />
        <mesh geometry={nodes['Node-Mesh_10'].geometry} material={materials['mat16.001']} />
        <mesh geometry={nodes['Node-Mesh_11'].geometry} material={materials['Mat.001']} />
        <mesh geometry={nodes['Node-Mesh_12'].geometry} material={materials['lambert3SG.003']} />
        <mesh geometry={nodes['Node-Mesh_13'].geometry} material={materials['mat9.003']} />
        <mesh geometry={nodes['Node-Mesh_14'].geometry} material={materials['mat20.001']} />
        <mesh geometry={nodes['Node-Mesh_15'].geometry} material={materials['mat21.005']} />
      </group>
      <mesh geometry={nodes.bookcaseClosedDoors002.geometry} material={materials.wood} position={[2.563, 0, -2.255]} scale={[5.497, 4.026, 2.812]} />
      <group position={[2.373, 0, -1.931]} scale={[4.026, 4.026, 2.812]}>
        <mesh geometry={nodes.doorLeft_1.geometry} material={materials.wood} />
        <mesh geometry={nodes.doorLeft_1_1.geometry} material={materials.metal} />
      </group>
      <group position={[2.373, 0, -1.931]} scale={[4.026, 4.026, 2.812]}>
        <mesh geometry={nodes.doorRight_1.geometry} material={materials.metal} />
        <mesh geometry={nodes.doorRight_1_1.geometry} material={materials.wood} />
      </group>
      <mesh geometry={nodes.group427675855.geometry} material={materials.mat19} position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]} />
      <mesh geometry={nodes.group1606767967.geometry} material={materials.mat20} position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]} />
      <mesh geometry={nodes.group1246942833.geometry} material={materials.mat20} position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]} />
      <group position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]}>
        <mesh geometry={nodes.mesh1103958513.geometry} material={materials.mat18} />
        <mesh geometry={nodes.mesh1103958513_1.geometry} material={materials.mat19} />
      </group>
      <group position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]}>
        <mesh geometry={nodes.mesh205479027.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh205479027_1.geometry} material={materials.mat18} />
      </group>
      <mesh geometry={nodes.group970697144.geometry} material={materials.mat17} position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]} />
      <mesh geometry={nodes.group848587833.geometry} material={materials.mat17} position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]} />
      <mesh geometry={nodes.group1840719534.geometry} material={materials.mat17} position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]} />
      <mesh geometry={nodes.group1477700025.geometry} material={materials.mat19} position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]} />
      <group position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]}>
        <mesh geometry={nodes.mesh1774544435.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh1774544435_1.geometry} material={materials.mat18} />
      </group>
      <mesh geometry={nodes.group1856349250.geometry} material={materials.mat19} position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]} />
      <mesh geometry={nodes.group298871933.geometry} material={materials.mat17} position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]} />
      <mesh geometry={nodes.group1512631129.geometry} material={materials.mat17} position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]} />
      <group position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]}>
        <mesh geometry={nodes.mesh2011576104.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh2011576104_1.geometry} material={materials.mat18} />
      </group>
      <group position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]}>
        <mesh geometry={nodes.mesh1024187379.geometry} material={materials.mat18} />
        <mesh geometry={nodes.mesh1024187379_1.geometry} material={materials.mat19} />
      </group>
      <group position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]}>
        <mesh geometry={nodes.mesh1785529362.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh1785529362_1.geometry} material={materials.mat18} />
      </group>
      <group position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]}>
        <mesh geometry={nodes.mesh451389640.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh451389640_1.geometry} material={materials.mat18} />
      </group>
      <group position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]}>
        <mesh geometry={nodes.mesh928384235.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh928384235_1.geometry} material={materials.mat18} />
      </group>
      <group position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]}>
        <mesh geometry={nodes.mesh765891613.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh765891613_1.geometry} material={materials.mat18} />
      </group>
      <group position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]}>
        <mesh geometry={nodes.mesh491062930.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh491062930_1.geometry} material={materials.mat18} />
      </group>
      <group position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]}>
        <mesh geometry={nodes.mesh830606209.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh830606209_1.geometry} material={materials.mat18} />
      </group>
      <group position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]}>
        <mesh geometry={nodes.mesh11767427.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh11767427_1.geometry} material={materials.mat18} />
      </group>
      <group position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]}>
        <mesh geometry={nodes.mesh1614564418.geometry} material={materials.mat18} />
        <mesh geometry={nodes.mesh1614564418_1.geometry} material={materials.mat19} />
      </group>
      <group position={[-2.572, 1.543, -0.172]} rotation={[Math.PI, -1.563, Math.PI]} scale={[1.402, 1.176, 1]}>
        <mesh geometry={nodes.mesh77709967.geometry} material={materials.mat19} />
        <mesh geometry={nodes.mesh77709967_1.geometry} material={materials.mat18} />
        <mesh geometry={nodes.mesh77709967_2.geometry} material={materials.mat17} />
      </group>
      <group position={[1.274, 0, -1.44]} scale={[3.451, 1, 3.451]}>
        <mesh geometry={nodes.rugRound_2.geometry} material={materials.carpet} />
        <mesh geometry={nodes.rugRound_2_1.geometry} material={materials.carpetDarker} />
      </group>
      <group position={[1.274, 0, -1.44]} scale={[3.451, 1, 3.451]}>
        <mesh geometry={nodes.rugRound_3.geometry} material={materials.carpetDarker} />
        <mesh geometry={nodes.rugRound_3_1.geometry} material={materials.carpet} />
      </group>
      <mesh geometry={nodes.FiddleleafFigPottedPlant_mesh.geometry} material={materials.FiddleleafFigPottedPlant_mat} position={[-2.078, 0, -1.635]} rotation={[0, -1.092, 0]} scale={[0.141, 0.287, 0.197]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Floor} />
      <mesh geometry={nodes.Plane001_1.geometry} material={materials.White} />
      <mesh geometry={nodes.Plane001_2.geometry} material={materials.Wall} />
      <mesh geometry={nodes.Plane001_3.geometry} material={materials.Glass} />
    </group>
  )
}

useGLTF.preload('models/office.glb')
